export * from "./hooks";
export * from "./types";
export {
  downloadsFetch,
  mediaOrganizeFetch,
  onlineMediaFetch,
  vfsFetch,
  videoFetch,
} from "./video-client";

import {
  apiDownloadManageList,
  apiMediaOrganizeCancel,
  apiMediaOrganizeClear,
  apiMediaOrganizeExecute,
  apiMediaOrganizeGetSession,
  apiMediaOrganizeIdentifyAll,
  apiMediaOrganizeIdentifyItem,
  apiMediaOrganizeResetMatch,
  apiMediaOrganizeScan,
  apiMediaOrganizeSelectAdultMatch,
  apiMediaOrganizeSelectMatch,
  apiMediaOrganizeSelectMusicMatch,
  apiMediaOrganizeUpdateTarget,
  apiOnlineMediaAnalyze,
  apiOnlineMediaStartDownload,
  apiPlaybackDeleteWatchHistory,
  apiPlaybackWatchHistory,
  apiVfsList,
  apiVfsProbe,
  apiVideoCreate,
  apiVideoDelete,
  apiVideoGetPersonDetail,
  apiVideoGetRecentlyAdded,
  apiVideoGetSyncProgress,
  apiVideoGetTvShowDetail,
  apiVideoGetVideoItemDetail,
  apiVideoList,
  apiVideoListCountries,
  apiVideoListGenres,
  apiVideoListTvShows,
  apiVideoListVideoItems,
  apiVideoSync,
  apiVideoToggleFavorite,
  apiVideoUpdate,
} from "./hooks";

export const api = {
  video: {
    list: apiVideoList,
    create: apiVideoCreate,
    update: apiVideoUpdate,
    delete: apiVideoDelete,
    sync: apiVideoSync,
    getSyncProgress: apiVideoGetSyncProgress,
    listVideoItems: apiVideoListVideoItems,
    listTvShows: apiVideoListTvShows,
    listGenres: apiVideoListGenres,
    listCountries: apiVideoListCountries,
    getRecentlyAdded: apiVideoGetRecentlyAdded,
    toggleFavorite: apiVideoToggleFavorite,
    getVideoItemDetail: apiVideoGetVideoItemDetail,
    getTvShowDetail: apiVideoGetTvShowDetail,
    getPersonDetail: apiVideoGetPersonDetail,
  },
  vfs: {
    list: apiVfsList,
    probe: apiVfsProbe,
  },
  onlineMedia: {
    analyze: apiOnlineMediaAnalyze,
    startDownload: apiOnlineMediaStartDownload,
  },
  mediaOrganize: {
    getSession: apiMediaOrganizeGetSession,
    scan: apiMediaOrganizeScan,
    identifyItem: apiMediaOrganizeIdentifyItem,
    identifyAll: apiMediaOrganizeIdentifyAll,
    selectMatch: apiMediaOrganizeSelectMatch,
    selectAdultMatch: apiMediaOrganizeSelectAdultMatch,
    selectMusicMatch: apiMediaOrganizeSelectMusicMatch,
    resetMatch: apiMediaOrganizeResetMatch,
    updateTarget: apiMediaOrganizeUpdateTarget,
    execute: apiMediaOrganizeExecute,
    cancel: apiMediaOrganizeCancel,
    clear: apiMediaOrganizeClear,
  },
  playback: {
    watchHistory: apiPlaybackWatchHistory,
    deleteWatchHistory: apiPlaybackDeleteWatchHistory,
  },
  downloadManage: {
    list: apiDownloadManageList,
  },
} as const;
