export * from "./hooks";
export * from "./types";
export {
  downloadsFetch,
  externalDbFetch,
  mediaOrganizeFetch,
  vfsFetch,
  videoFetch,
  videoOnlineMediaFetch,
} from "./video-client";

import {
  apiDownloadManageList,
  apiExternalDbGetTmdb,
  apiExternalDbStatus,
  apiExternalDbTestTmdb,
  apiExternalDbUpdateTmdb,
  apiMediaOrganizeCancel,
  apiMediaOrganizeClear,
  apiMediaOrganizeExecute,
  apiMediaOrganizeGetSession,
  apiMediaOrganizeIdentifyAll,
  apiMediaOrganizeIdentifyItem,
  apiMediaOrganizeResetMatch,
  apiMediaOrganizeScan,
  apiMediaOrganizeSelectAdultMatch,
  apiMediaOrganizeSelectMatch,
  apiMediaOrganizeSelectMusicMatch,
  apiMediaOrganizeUpdateTarget,
  apiPlaybackDeleteWatchHistory,
  apiPlaybackReportProgress,
  apiPlaybackWatchHistory,
  apiVfsList,
  apiVfsProbe,
  apiVideoCreate,
  apiVideoDelete,
  apiVideoGetPersonDetail,
  apiVideoGetRecentlyAdded,
  apiVideoGetSyncProgress,
  apiVideoGetTvShowDetail,
  apiVideoGetVideoItemDetail,
  apiVideoList,
  apiVideoListCountries,
  apiVideoListGenres,
  apiVideoListTvShows,
  apiVideoListVideoItems,
  apiVideoOnlineMediaAnalyze,
  apiVideoOnlineMediaAuthSettings,
  apiVideoOnlineMediaProviders,
  apiVideoOnlineMediaStartDownload,
  apiVideoOnlineMediaUpdateAuthSetting,
  apiVideoSync,
  apiVideoToggleFavorite,
  apiVideoUpdate,
  apiVideoYtdlpStatus,
  apiVideoYtdlpUpdate,
} from "./hooks";

export const api = {
  video: {
    list: apiVideoList,
    create: apiVideoCreate,
    update: apiVideoUpdate,
    delete: apiVideoDelete,
    sync: apiVideoSync,
    getSyncProgress: apiVideoGetSyncProgress,
    listVideoItems: apiVideoListVideoItems,
    listTvShows: apiVideoListTvShows,
    listGenres: apiVideoListGenres,
    listCountries: apiVideoListCountries,
    getRecentlyAdded: apiVideoGetRecentlyAdded,
    toggleFavorite: apiVideoToggleFavorite,
    getVideoItemDetail: apiVideoGetVideoItemDetail,
    getTvShowDetail: apiVideoGetTvShowDetail,
    getPersonDetail: apiVideoGetPersonDetail,
    ytdlpStatus: apiVideoYtdlpStatus,
    updateYtdlp: apiVideoYtdlpUpdate,
  },
  vfs: {
    list: apiVfsList,
    probe: apiVfsProbe,
  },
  videoOnlineMedia: {
    analyze: apiVideoOnlineMediaAnalyze,
    startDownload: apiVideoOnlineMediaStartDownload,
    providers: apiVideoOnlineMediaProviders,
    authSettings: apiVideoOnlineMediaAuthSettings,
    updateAuthSetting: apiVideoOnlineMediaUpdateAuthSetting,
  },
  mediaOrganize: {
    getSession: apiMediaOrganizeGetSession,
    scan: apiMediaOrganizeScan,
    identifyItem: apiMediaOrganizeIdentifyItem,
    identifyAll: apiMediaOrganizeIdentifyAll,
    selectMatch: apiMediaOrganizeSelectMatch,
    selectAdultMatch: apiMediaOrganizeSelectAdultMatch,
    selectMusicMatch: apiMediaOrganizeSelectMusicMatch,
    resetMatch: apiMediaOrganizeResetMatch,
    updateTarget: apiMediaOrganizeUpdateTarget,
    execute: apiMediaOrganizeExecute,
    cancel: apiMediaOrganizeCancel,
    clear: apiMediaOrganizeClear,
  },
  playback: {
    watchHistory: apiPlaybackWatchHistory,
    deleteWatchHistory: apiPlaybackDeleteWatchHistory,
    reportProgress: apiPlaybackReportProgress,
  },
  downloadManage: {
    list: apiDownloadManageList,
  },
  externalDb: {
    status: apiExternalDbStatus,
    getTmdb: apiExternalDbGetTmdb,
    updateTmdb: apiExternalDbUpdateTmdb,
    testTmdb: apiExternalDbTestTmdb,
  },
} as const;
