//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ai_agents")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "ai_agents_user_id_name_key")]
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text", unique_key = "ai_agents_user_id_name_key")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub avatar: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub system_prompt: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub default_model: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub default_provider: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub model_params: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub tags: Option<Json>,
    pub is_default: bool,
    pub is_builtin: bool,
    pub sort_order: i32,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub draft: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", unique)]
    pub username: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::agent_scheduled_triggers::Entity")]
    AgentScheduledTriggers,
    #[sea_orm(has_many = "super::ai_conversations::Entity")]
    AiConversations,
    #[sea_orm(has_many = "super::channels::Entity")]
    Channels,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Users,
}

impl Related<super::agent_scheduled_triggers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentScheduledTriggers.def()
    }
}

impl Related<super::ai_conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiConversations.def()
    }
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channels.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
