//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ai_conversations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub agent_id: Uuid,
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub pinned: bool,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub source_channel_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub context: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub session_memory_path: Option<String>,
    pub session_memory_updated_at: Option<DateTimeWithTimeZone>,
    pub last_prompt_tokens: Option<i32>,
    pub last_completion_tokens: Option<i32>,
    pub last_usage_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ai_agents::Entity",
        from = "Column::AgentId",
        to = "super::ai_agents::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AiAgents,
    #[sea_orm(has_many = "super::ai_message_attachments::Entity")]
    AiMessageAttachments,
    #[sea_orm(has_many = "super::ai_messages::Entity")]
    AiMessages,
    #[sea_orm(has_many = "super::channel_user_conversations::Entity")]
    ChannelUserConversations,
    #[sea_orm(
        belongs_to = "super::channels::Entity",
        from = "Column::SourceChannelId",
        to = "super::channels::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Channels,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::ai_agents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiAgents.def()
    }
}

impl Related<super::ai_message_attachments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiMessageAttachments.def()
    }
}

impl Related<super::ai_messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiMessages.def()
    }
}

impl Related<super::channel_user_conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelUserConversations.def()
    }
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channels.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
