//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ai_message_attachments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub message_id: Uuid,
    pub conversation_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub file_type: String,
    #[sea_orm(column_type = "Text")]
    pub file_name: String,
    pub file_size: i32,
    #[sea_orm(column_type = "Text")]
    pub storage_key: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub hash: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ai_conversations::Entity",
        from = "Column::ConversationId",
        to = "super::ai_conversations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AiConversations,
    #[sea_orm(
        belongs_to = "super::ai_messages::Entity",
        from = "Column::MessageId",
        to = "super::ai_messages::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AiMessages,
}

impl Related<super::ai_conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiConversations.def()
    }
}

impl Related<super::ai_messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiMessages.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
