//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ai_messages")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub conversation_id: Uuid,
    pub ref_id: Option<Uuid>,
    pub link_id: Option<Uuid>,
    pub turn_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub role: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub input_tokens: Option<i32>,
    pub output_tokens: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub model: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ai_conversations::Entity",
        from = "Column::ConversationId",
        to = "super::ai_conversations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AiConversations,
    #[sea_orm(has_many = "super::ai_message_attachments::Entity")]
    AiMessageAttachments,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::LinkId",
        to = "Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    SelfRef2,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::RefId",
        to = "Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    SelfRef1,
    #[sea_orm(has_one = "super::ai_runs::Entity")]
    AiRuns,
}

impl Related<super::ai_conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiConversations.def()
    }
}

impl Related<super::ai_message_attachments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiMessageAttachments.def()
    }
}

impl Related<super::ai_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiRuns.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
