//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ai_runs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub parent_conversation_id: Uuid,
    #[sea_orm(unique)]
    pub parent_tool_use_id: Uuid,
    #[sea_orm(unique)]
    pub child_conversation_id: Option<Uuid>,
    pub parent_agent_id: Option<Uuid>,
    pub child_agent_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub skill_name: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub params: Json,
    #[sea_orm(column_type = "Text")]
    pub user_input: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub output: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    pub started_at: DateTimeWithTimeZone,
    pub ended_at: Option<DateTimeWithTimeZone>,
    pub duration_ms: Option<i32>,
    pub input_tokens: Option<i32>,
    pub output_tokens: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ai_agents::Entity",
        from = "Column::ChildAgentId",
        to = "super::ai_agents::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AiAgents2,
    #[sea_orm(
        belongs_to = "super::ai_agents::Entity",
        from = "Column::ParentAgentId",
        to = "super::ai_agents::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AiAgents1,
    #[sea_orm(
        belongs_to = "super::ai_conversations::Entity",
        from = "Column::ChildConversationId",
        to = "super::ai_conversations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AiConversations2,
    #[sea_orm(
        belongs_to = "super::ai_conversations::Entity",
        from = "Column::ParentConversationId",
        to = "super::ai_conversations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AiConversations1,
    #[sea_orm(
        belongs_to = "super::ai_messages::Entity",
        from = "Column::ParentToolUseId",
        to = "super::ai_messages::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AiMessages,
}

impl Related<super::ai_messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiMessages.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
