//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "album_genres")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub album_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub genre_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::genres::Entity",
        from = "Column::GenreId",
        to = "super::genres::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Genres,
    #[sea_orm(
        belongs_to = "super::music_albums::Entity",
        from = "Column::AlbumId",
        to = "super::music_albums::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MusicAlbums,
}

impl Related<super::genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Genres.def()
    }
}

impl Related<super::music_albums::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MusicAlbums.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
