//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "book_volumes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "book_volumes_book_id_volume_number_key")]
    pub book_id: Uuid,
    #[sea_orm(unique_key = "book_volumes_book_id_volume_number_key")]
    pub volume_number: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    pub word_count: Option<i32>,
    pub chapter_count: Option<i32>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::book_chapters::Entity")]
    BookChapters,
    #[sea_orm(
        belongs_to = "super::book_items::Entity",
        from = "Column::BookId",
        to = "super::book_items::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BookItems,
}

impl Related<super::book_chapters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookChapters.def()
    }
}

impl Related<super::book_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
