//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "book_chapters")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub book_id: Uuid,
    pub volume_id: Option<Uuid>,
    pub chapter_number: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    pub word_count: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub file_path: Option<String>,
    pub is_vip: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_chapter_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_url: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::book_items::Entity",
        from = "Column::BookId",
        to = "super::book_items::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BookItems,
    #[sea_orm(
        belongs_to = "super::book_volumes::Entity",
        from = "Column::VolumeId",
        to = "super::book_volumes::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    BookVolumes,
}

impl Related<super::book_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookItems.def()
    }
}

impl Related<super::book_volumes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookVolumes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
