//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "book_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub book_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub author: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub original_title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sort_title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub overview: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cover_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub serial_status: Option<String>,
    pub word_count: Option<i32>,
    pub year: Option<i32>,
    pub last_updated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "book_items_source_provider_source_book_id_key"
    )]
    pub source_provider: Option<String>,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "book_items_source_provider_source_book_id_key"
    )]
    pub source_book_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_url: Option<String>,
    pub is_adult: bool,
    pub is_favorite: bool,
    pub locked_fields: Option<Vec<String>>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub douban_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub bangumi_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub qidian_id: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub douban_rating: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub bangumi_rating: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub isbn: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub publisher: Option<String>,
    pub scraped_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::book_chapters::Entity")]
    BookChapters,
    #[sea_orm(has_many = "super::book_collections::Entity")]
    BookCollections,
    #[sea_orm(has_many = "super::book_files::Entity")]
    BookFiles,
    #[sea_orm(has_many = "super::book_genres::Entity")]
    BookGenres,
    #[sea_orm(has_many = "super::book_volumes::Entity")]
    BookVolumes,
    #[sea_orm(
        belongs_to = "super::books::Entity",
        from = "Column::BookId",
        to = "super::books::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Books,
    #[sea_orm(has_many = "super::media_arts::Entity")]
    MediaArts,
    #[sea_orm(has_many = "super::user_media_ratings::Entity")]
    UserMediaRatings,
    #[sea_orm(has_many = "super::user_media_states::Entity")]
    UserMediaStates,
}

impl Related<super::book_chapters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookChapters.def()
    }
}

impl Related<super::book_collections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookCollections.def()
    }
}

impl Related<super::book_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookFiles.def()
    }
}

impl Related<super::book_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookGenres.def()
    }
}

impl Related<super::book_volumes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookVolumes.def()
    }
}

impl Related<super::books::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Books.def()
    }
}

impl Related<super::media_arts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaArts.def()
    }
}

impl Related<super::user_media_ratings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMediaRatings.def()
    }
}

impl Related<super::user_media_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMediaStates.def()
    }
}

impl Related<super::collections::Entity> for Entity {
    fn to() -> RelationDef {
        super::book_collections::Relation::Collections.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::book_collections::Relation::BookItems.def().rev())
    }
}

impl Related<super::genres::Entity> for Entity {
    fn to() -> RelationDef {
        super::book_genres::Relation::Genres.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::book_genres::Relation::BookItems.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
