//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ChannelDirection;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "channels")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub config: Json,
    pub direction: ChannelDirection,
    pub sort_order: i32,
    pub user_id: Option<Uuid>,
    pub agent_id: Option<Uuid>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ai_agents::Entity",
        from = "Column::AgentId",
        to = "super::ai_agents::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    AiAgents,
    #[sea_orm(has_many = "super::ai_conversations::Entity")]
    AiConversations,
    #[sea_orm(has_many = "super::channel_user_conversations::Entity")]
    ChannelUserConversations,
    #[sea_orm(has_many = "super::channel_webpush_subscriptions::Entity")]
    ChannelWebpushSubscriptions,
    #[sea_orm(has_many = "super::notification_source_channels::Entity")]
    NotificationSourceChannels,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::ai_agents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiAgents.def()
    }
}

impl Related<super::ai_conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiConversations.def()
    }
}

impl Related<super::channel_user_conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelUserConversations.def()
    }
}

impl Related<super::channel_webpush_subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelWebpushSubscriptions.def()
    }
}

impl Related<super::notification_source_channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationSourceChannels.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::notification_sources::Entity> for Entity {
    fn to() -> RelationDef {
        super::notification_source_channels::Relation::NotificationSources.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::notification_source_channels::Relation::Channels.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
