//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "channel_user_conversations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "channel_user_conversations_channel_id_external_user_id_key")]
    pub channel_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "channel_user_conversations_channel_id_external_user_id_key"
    )]
    pub external_user_id: String,
    pub current_conversation_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub external_thread_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ai_conversations::Entity",
        from = "Column::CurrentConversationId",
        to = "super::ai_conversations::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    AiConversations,
    #[sea_orm(
        belongs_to = "super::channels::Entity",
        from = "Column::ChannelId",
        to = "super::channels::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Channels,
}

impl Related<super::ai_conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiConversations.def()
    }
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channels.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
