//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "video", table_name = "chapters")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "chapters_file_id_index_key")]
    pub file_id: Uuid,
    #[sea_orm(unique_key = "chapters_file_id_index_key")]
    pub index: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    pub start_time: i32,
    pub end_time: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub thumb_path: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::video_files::Entity",
        from = "Column::FileId",
        to = "super::video_files::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    VideoFiles,
}

impl Related<super::video_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoFiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
