//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "collections")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub sort_title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub overview: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub poster_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub backdrop_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub tmdb_collection_id: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::book_collections::Entity")]
    BookCollections,
    #[sea_orm(has_many = "super::tv_show_collections::Entity")]
    TvShowCollections,
    #[sea_orm(has_many = "super::video_collections::Entity")]
    VideoCollections,
}

impl Related<super::book_collections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookCollections.def()
    }
}

impl Related<super::tv_show_collections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TvShowCollections.def()
    }
}

impl Related<super::video_collections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoCollections.def()
    }
}

impl Related<super::book_items::Entity> for Entity {
    fn to() -> RelationDef {
        super::book_collections::Relation::BookItems.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::book_collections::Relation::Collections.def().rev())
    }
}

impl Related<super::tv_shows::Entity> for Entity {
    fn to() -> RelationDef {
        super::tv_show_collections::Relation::TvShows.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::tv_show_collections::Relation::Collections.def().rev())
    }
}

impl Related<super::video_items::Entity> for Entity {
    fn to() -> RelationDef {
        super::video_collections::Relation::VideoItems.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::video_collections::Relation::Collections.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
