//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "desktop_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub desktop_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    pub x: i32,
    pub y: i32,
    pub w: i32,
    pub h: i32,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub config: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_desktops::Entity",
        from = "Column::DesktopId",
        to = "super::user_desktops::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UserDesktops,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::user_desktops::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserDesktops.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
