//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "docs_spaces")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub avatar: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub sort_order: i32,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub root_path: Option<String>,
    pub vfs_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::docs_node_meta::Entity")]
    DocsNodeMeta,
    #[sea_orm(
        belongs_to = "super::vfs::Entity",
        from = "Column::VfsId",
        to = "super::vfs::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Vfs,
}

impl Related<super::docs_node_meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocsNodeMeta.def()
    }
}

impl Related<super::vfs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vfs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
