//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "docs_node_view_states")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "docs_node_view_states_user_id_space_id_rel_path_key")]
    pub user_id: Uuid,
    #[sea_orm(unique_key = "docs_node_view_states_user_id_space_id_rel_path_key")]
    pub space_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "docs_node_view_states_user_id_space_id_rel_path_key"
    )]
    pub rel_path: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub view_state: Json,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
