//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "docs_node_meta")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub space_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub rel_path: String,
    pub is_favorite: bool,
    pub is_pinned: bool,
    pub is_archived: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cover_image: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub tags: Option<Json>,
    pub last_opened_at: Option<DateTimeWithTimeZone>,
    pub sort_order: i32,
    pub word_count: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::docs_spaces::Entity",
        from = "Column::SpaceId",
        to = "super::docs_spaces::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DocsSpaces,
}

impl Related<super::docs_spaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocsSpaces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
