//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

//! Shared public table; video sidecar must access it via bus/main-server APIs and must not write it directly.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "video", table_name = "download_records")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub torrent_hash: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub app_id: String,
    #[sea_orm(column_type = "Text")]
    pub downloader_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_site: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_url: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub app_metadata: Option<Json>,
    pub download_client_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub download_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub target_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub file_size: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub thumbnail_url: Option<String>,
    pub download_speed: Option<i64>,
    pub eta_seconds: Option<i32>,
    pub downloaded_bytes: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub progress: f64,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub completed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::download_clients::Entity",
        from = "Column::DownloadClientId",
        to = "super::download_clients::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    DownloadClients,
}

impl Related<super::download_clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DownloadClients.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
