//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "episodes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tv_show_id: Uuid,
    #[sea_orm(unique_key = "episodes_season_id_episode_number_key")]
    pub season_id: Uuid,
    #[sea_orm(unique_key = "episodes_season_id_episode_number_key")]
    pub episode_number: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub overview: Option<String>,
    pub air_date: Option<Date>,
    pub runtime: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub still_path: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub tmdb_rating: Option<f64>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub tmdb_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::seasons::Entity",
        from = "Column::SeasonId",
        to = "super::seasons::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Seasons,
    #[sea_orm(
        belongs_to = "super::tv_shows::Entity",
        from = "Column::TvShowId",
        to = "super::tv_shows::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TvShows,
    #[sea_orm(has_many = "super::user_media_states::Entity")]
    UserMediaStates,
    #[sea_orm(has_many = "super::video_files::Entity")]
    VideoFiles,
}

impl Related<super::seasons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Seasons.def()
    }
}

impl Related<super::tv_shows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TvShows.def()
    }
}

impl Related<super::user_media_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMediaStates.def()
    }
}

impl Related<super::video_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoFiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
