//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

//! Shared public table; video sidecar must access it via bus/main-server APIs and must not write it directly.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "video", table_name = "file_favorites")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "file_favorites_user_id_vfs_id_path_key")]
    pub user_id: Uuid,
    #[sea_orm(unique_key = "file_favorites_user_id_vfs_id_path_key")]
    pub vfs_id: Uuid,
    #[sea_orm(column_type = "Text", unique_key = "file_favorites_user_id_vfs_id_path_key")]
    pub path: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub is_directory: bool,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
    #[sea_orm(
        belongs_to = "super::vfs::Entity",
        from = "Column::VfsId",
        to = "super::vfs::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Vfs,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::vfs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vfs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
