//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

//! Shared public table; video sidecar must access it via bus/main-server APIs and must not write it directly.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "video", table_name = "genres")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub tmdb_genre_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    // AlbumGenres and BookGenres removed - entities no longer in video app
    #[sea_orm(has_many = "super::tv_show_genres::Entity")]
    TvShowGenres,
    #[sea_orm(has_many = "super::video_genres::Entity")]
    VideoGenres,
}

// Album and book genre relations removed - entities no longer in video app
/*
impl Related<super::album_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumGenres.def()
    }
}

impl Related<super::book_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookGenres.def()
    }
}
*/

impl Related<super::tv_show_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TvShowGenres.def()
    }
}

impl Related<super::video_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoGenres.def()
    }
}

// Book items and music albums relations removed - entities no longer in video app
/*
impl Related<super::book_items::Entity> for Entity {
    fn to() -> RelationDef {
        super::book_genres::Relation::BookItems.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::book_genres::Relation::Genres.def().rev())
    }
}

impl Related<super::music_albums::Entity> for Entity {
    fn to() -> RelationDef {
        super::album_genres::Relation::MusicAlbums.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::album_genres::Relation::Genres.def().rev())
    }
}
*/

impl Related<super::tv_shows::Entity> for Entity {
    fn to() -> RelationDef {
        super::tv_show_genres::Relation::TvShows.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::tv_show_genres::Relation::Genres.def().rev())
    }
}

impl Related<super::video_items::Entity> for Entity {
    fn to() -> RelationDef {
        super::video_genres::Relation::VideoItems.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::video_genres::Relation::Genres.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
