//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "inbox_notifications")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "inbox_notifications_user_id_dedupe_key_key")]
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub app_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub category_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub level: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub body: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub action: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub read: bool,
    pub dismissed: bool,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "inbox_notifications_user_id_dedupe_key_key"
    )]
    pub dedupe_key: Option<String>,
    pub progress: Option<i32>,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
