//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mail_attachments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub message_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub filename: String,
    #[sea_orm(column_type = "Text")]
    pub content_type: String,
    pub size: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub data: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::mail_messages::Entity",
        from = "Column::MessageId",
        to = "super::mail_messages::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MailMessages,
}

impl Related<super::mail_messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MailMessages.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
