//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mail_messages")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "mail_messages_account_id_folder_id_uid_key")]
    pub account_id: Uuid,
    #[sea_orm(unique_key = "mail_messages_account_id_folder_id_uid_key")]
    pub folder_id: Uuid,
    #[sea_orm(unique_key = "mail_messages_account_id_folder_id_uid_key")]
    pub uid: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub message_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub subject: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub from_addrs: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub to_addrs: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub cc_addrs: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub bcc_addrs: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub reply_to_addrs: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub in_reply_to: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub refs: Option<String>,
    pub date: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub text_body: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub html_body: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub preview: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub flags: Json,
    pub is_read: bool,
    pub is_flagged: bool,
    pub has_attachments: bool,
    pub size: i32,
    pub body_fetched: bool,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::mail_accounts::Entity",
        from = "Column::AccountId",
        to = "super::mail_accounts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MailAccounts,
    #[sea_orm(has_many = "super::mail_attachments::Entity")]
    MailAttachments,
    #[sea_orm(
        belongs_to = "super::mail_folders::Entity",
        from = "Column::FolderId",
        to = "super::mail_folders::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MailFolders,
}

impl Related<super::mail_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MailAccounts.def()
    }
}

impl Related<super::mail_attachments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MailAttachments.def()
    }
}

impl Related<super::mail_folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MailFolders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
