//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "media_arts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub video_item_id: Option<Uuid>,
    pub tv_show_id: Option<Uuid>,
    pub season_id: Option<Uuid>,
    pub album_id: Option<Uuid>,
    pub book_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub art_type: String,
    #[sea_orm(column_type = "Text")]
    pub url: String,
    pub width: Option<i32>,
    pub height: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub language: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source: Option<String>,
    pub is_selected: bool,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::book_items::Entity",
        from = "Column::BookId",
        to = "super::book_items::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BookItems,
    #[sea_orm(
        belongs_to = "super::music_albums::Entity",
        from = "Column::AlbumId",
        to = "super::music_albums::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MusicAlbums,
    #[sea_orm(
        belongs_to = "super::seasons::Entity",
        from = "Column::SeasonId",
        to = "super::seasons::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Seasons,
    #[sea_orm(
        belongs_to = "super::tv_shows::Entity",
        from = "Column::TvShowId",
        to = "super::tv_shows::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TvShows,
    #[sea_orm(
        belongs_to = "super::video_items::Entity",
        from = "Column::VideoItemId",
        to = "super::video_items::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    VideoItems,
}

impl Related<super::book_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookItems.def()
    }
}

impl Related<super::music_albums::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MusicAlbums.def()
    }
}

impl Related<super::seasons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Seasons.def()
    }
}

impl Related<super::tv_shows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TvShows.def()
    }
}

impl Related<super::video_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
