//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "music_album_artists")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "music_album_artists_album_id_artist_id_role_key")]
    pub album_id: Uuid,
    #[sea_orm(unique_key = "music_album_artists_album_id_artist_id_role_key")]
    pub artist_id: Uuid,
    #[sea_orm(column_type = "Text", unique_key = "music_album_artists_album_id_artist_id_role_key")]
    pub role: String,
    pub sort_order: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::music_albums::Entity",
        from = "Column::AlbumId",
        to = "super::music_albums::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MusicAlbums,
    #[sea_orm(
        belongs_to = "super::music_artists::Entity",
        from = "Column::ArtistId",
        to = "super::music_artists::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MusicArtists,
}

impl Related<super::music_albums::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MusicAlbums.def()
    }
}

impl Related<super::music_artists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MusicArtists.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
