//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "music_albums")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub music_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub sort_title: Option<String>,
    pub year: Option<i32>,
    pub release_date: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub album_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub mb_album_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cover_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub overview: Option<String>,
    pub total_tracks: Option<i32>,
    pub total_discs: Option<i32>,
    pub is_favorite: bool,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub scraped_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::album_genres::Entity")]
    AlbumGenres,
    #[sea_orm(has_many = "super::media_arts::Entity")]
    MediaArts,
    #[sea_orm(has_many = "super::music_album_artists::Entity")]
    MusicAlbumArtists,
    #[sea_orm(has_many = "super::music_tracks::Entity")]
    MusicTracks,
    #[sea_orm(
        belongs_to = "super::musics::Entity",
        from = "Column::MusicId",
        to = "super::musics::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Musics,
}

impl Related<super::album_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumGenres.def()
    }
}

impl Related<super::media_arts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaArts.def()
    }
}

impl Related<super::music_album_artists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MusicAlbumArtists.def()
    }
}

impl Related<super::music_tracks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MusicTracks.def()
    }
}

impl Related<super::musics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Musics.def()
    }
}

impl Related<super::genres::Entity> for Entity {
    fn to() -> RelationDef {
        super::album_genres::Relation::Genres.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::album_genres::Relation::MusicAlbums.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
