//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "music_artists")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub original_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub biography: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub profile_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub profile_key: Option<String>,
    pub popularity: Option<i32>,
    pub followers: Option<i32>,
    pub genres: Option<Vec<String>>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub mb_id: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::music_album_artists::Entity")]
    MusicAlbumArtists,
}

impl Related<super::music_album_artists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MusicAlbumArtists.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
