//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "notification_sources")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "notification_sources_user_id_app_id_category_id_key")]
    pub user_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "notification_sources_user_id_app_id_category_id_key"
    )]
    pub app_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "notification_sources_user_id_app_id_category_id_key"
    )]
    pub category_id: String,
    #[sea_orm(column_type = "Text")]
    pub label: String,
    pub is_enabled: bool,
    #[sea_orm(column_type = "Text")]
    pub display_mode: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::notification_source_channels::Entity")]
    NotificationSourceChannels,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::notification_source_channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationSourceChannels.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        super::notification_source_channels::Relation::Channels.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::notification_source_channels::Relation::NotificationSources
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
