//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "notification_source_channels")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub source_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub channel_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channels::Entity",
        from = "Column::ChannelId",
        to = "super::channels::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Channels,
    #[sea_orm(
        belongs_to = "super::notification_sources::Entity",
        from = "Column::SourceId",
        to = "super::notification_sources::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    NotificationSources,
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channels.def()
    }
}

impl Related<super::notification_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationSources.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
