//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "organize_reports")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub source_path: String,
    #[sea_orm(column_type = "Text")]
    pub total_items: String,
    #[sea_orm(column_type = "Text")]
    pub success_count: String,
    #[sea_orm(column_type = "Text")]
    pub failed_count: String,
    #[sea_orm(column_type = "Text")]
    pub skipped_count: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub results: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub media_names: Json,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
