//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "video", table_name = "playback_sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub session_id: Option<Uuid>,
    pub file_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub play_method: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_container: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_video_codec: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_video_profile: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_hdr_type: Option<String>,
    pub source_width: Option<i32>,
    pub source_height: Option<i32>,
    pub source_duration: Option<i32>,
    pub source_file_size: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub transcode_video_codec: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub transcode_audio_codec: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub transcode_reasons: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub media_streams_raw: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub client_capabilities: Option<Json>,
    pub position: i32,
    pub started_at: DateTimeWithTimeZone,
    pub last_seen_at: DateTimeWithTimeZone,
    pub stopped_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sessions::Entity",
        from = "Column::SessionId",
        to = "super::sessions::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Sessions,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
    #[sea_orm(
        belongs_to = "super::video_files::Entity",
        from = "Column::FileId",
        to = "super::video_files::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    VideoFiles,
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::video_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoFiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
