//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "pt_sites")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub site_id: String,
    #[sea_orm(column_type = "Text")]
    pub domain: String,
    #[sea_orm(column_type = "Text")]
    pub auth_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub cookies: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub api_key: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub config_yaml: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub config_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub auto_stop_minutes: Option<String>,
    pub traffic_manage_enabled: bool,
    #[sea_orm(column_type = "Text")]
    pub traffic_manage_mode: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub traffic_manage_target: Option<String>,
    pub adult_enabled: bool,
    pub sort_order: i32,
    pub last_checked_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::download_records::Entity")]
    DownloadRecords,
}

impl Related<super::download_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DownloadRecords.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
