//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "scheduled_task_logs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub task_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub exit_code: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub stdout: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub stderr: Option<String>,
    pub started_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub duration: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::scheduled_tasks::Entity",
        from = "Column::TaskId",
        to = "super::scheduled_tasks::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ScheduledTasks,
}

impl Related<super::scheduled_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScheduledTasks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
