//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "seasons")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "seasons_tv_show_id_season_number_key")]
    pub tv_show_id: Uuid,
    #[sea_orm(unique_key = "seasons_tv_show_id_season_number_key")]
    pub season_number: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub overview: Option<String>,
    pub air_date: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub poster_path: Option<String>,
    pub episode_count: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::episodes::Entity")]
    Episodes,
    #[sea_orm(has_many = "super::media_arts::Entity")]
    MediaArts,
    #[sea_orm(has_many = "super::tv_season_cast::Entity")]
    TvSeasonCast,
    #[sea_orm(
        belongs_to = "super::tv_shows::Entity",
        from = "Column::TvShowId",
        to = "super::tv_shows::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TvShows,
}

impl Related<super::episodes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Episodes.def()
    }
}

impl Related<super::media_arts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaArts.def()
    }
}

impl Related<super::tv_season_cast::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TvSeasonCast.def()
    }
}

impl Related<super::tv_shows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TvShows.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
