//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

//! Shared public table; video sidecar must access it via bus/main-server APIs and must not write it directly.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "video", table_name = "sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub expires_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub browser: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub browser_version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub os: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::playback_sessions::Entity")]
    PlaybackSessions,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Users,
    #[sea_orm(has_many = "super::watch_histories::Entity")]
    WatchHistories,
}

impl Related<super::playback_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaybackSessions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::watch_histories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WatchHistories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
