//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "share_links")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub token: String,
    pub owner_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub resource_type: String,
    pub resource_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resource_path: Option<String>,
    pub file_system_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub resource_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub cover_image: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub password_hash: Option<String>,
    pub max_access_count: Option<i32>,
    pub access_count: i32,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::share_link_accesses::Entity")]
    ShareLinkAccesses,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::share_link_accesses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShareLinkAccesses.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
