//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "subscription_filters")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub sources: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub resolutions: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub codecs: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub release_groups: Option<Json>,
    #[sea_orm(column_type = "Text")]
    pub min_size: String,
    #[sea_orm(column_type = "Text")]
    pub max_size: String,
    #[sea_orm(column_type = "Text")]
    pub min_seeders: String,
    #[sea_orm(column_type = "Text")]
    pub max_seeders: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub include_keywords: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exclude_keywords: Option<String>,
    pub free_only: bool,
    pub exclude_hr: bool,
    pub sort_order: i32,
    pub created_by: Option<Uuid>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::subscriptions::Entity")]
    Subscriptions,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscriptions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
