//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "subscriptions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub subscription_mode: String,
    #[sea_orm(column_type = "Text")]
    pub media_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub tmdb_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub year: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub poster_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub season: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub episodes: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub series_prefix: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata_source: Option<String>,
    pub max_downloads_per_run: i32,
    pub filter_id: Option<Uuid>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub filter_ids: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub filter_overrides: Option<Json>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub interval_minutes: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub site_ids: Option<Json>,
    pub download_client_id: Option<Uuid>,
    pub target_video_id: Option<Uuid>,
    pub last_checked_at: Option<DateTimeWithTimeZone>,
    pub next_check_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<Uuid>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::download_clients::Entity",
        from = "Column::DownloadClientId",
        to = "super::download_clients::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    DownloadClients,
    #[sea_orm(has_many = "super::download_records::Entity")]
    DownloadRecords,
    #[sea_orm(
        belongs_to = "super::subscription_filters::Entity",
        from = "Column::FilterId",
        to = "super::subscription_filters::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    SubscriptionFilters,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Users,
    #[sea_orm(
        belongs_to = "super::videos::Entity",
        from = "Column::TargetVideoId",
        to = "super::videos::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Videos,
}

impl Related<super::download_clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DownloadClients.def()
    }
}

impl Related<super::download_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DownloadRecords.def()
    }
}

impl Related<super::subscription_filters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubscriptionFilters.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::videos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Videos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
