//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "video", table_name = "tv_season_cast")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tv_show_id: Uuid,
    #[sea_orm(unique_key = "tv_season_cast_season_id_tv_person_id_role_key")]
    pub season_id: Uuid,
    #[sea_orm(unique_key = "tv_season_cast_season_id_tv_person_id_role_key")]
    pub tv_person_id: Uuid,
    #[sea_orm(column_type = "Text", unique_key = "tv_season_cast_season_id_tv_person_id_role_key")]
    pub role: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub character: Option<String>,
    pub sort_order: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::seasons::Entity",
        from = "Column::SeasonId",
        to = "super::seasons::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Seasons,
    #[sea_orm(
        belongs_to = "super::tv_persons::Entity",
        from = "Column::TvPersonId",
        to = "super::tv_persons::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TvPersons,
    #[sea_orm(
        belongs_to = "super::tv_shows::Entity",
        from = "Column::TvShowId",
        to = "super::tv_shows::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TvShows,
}

impl Related<super::seasons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Seasons.def()
    }
}

impl Related<super::tv_persons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TvPersons.def()
    }
}

impl Related<super::tv_shows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TvShows.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
