//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tv_show_collections")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tv_show_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub collection_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::collections::Entity",
        from = "Column::CollectionId",
        to = "super::collections::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Collections,
    #[sea_orm(
        belongs_to = "super::tv_shows::Entity",
        from = "Column::TvShowId",
        to = "super::tv_shows::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TvShows,
}

impl Related<super::collections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Collections.def()
    }
}

impl Related<super::tv_shows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TvShows.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
