//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

//! Shared public table; video sidecar must access it via bus/main-server APIs and must not write it directly.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub username: String,
    #[sea_orm(column_type = "Text")]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub password_hash: String,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub otp_enabled: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub otp_secret: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::file_favorites::Entity")]
    FileFavorites,
    #[sea_orm(has_many = "super::playback_sessions::Entity")]
    PlaybackSessions,
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
    #[sea_orm(has_many = "super::subscription_filters::Entity")]
    SubscriptionFilters,
    #[sea_orm(has_many = "super::subscriptions::Entity")]
    Subscriptions,
    #[sea_orm(has_many = "super::user_media_ratings::Entity")]
    UserMediaRatings,
    #[sea_orm(has_many = "super::user_media_states::Entity")]
    UserMediaStates,
    #[sea_orm(has_many = "super::user_preferences::Entity")]
    UserPreferences,
    #[sea_orm(has_many = "super::watch_histories::Entity")]
    WatchHistories,
}

impl Related<super::file_favorites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileFavorites.def()
    }
}

impl Related<super::playback_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaybackSessions.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::subscription_filters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubscriptionFilters.def()
    }
}

impl Related<super::subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscriptions.def()
    }
}

impl Related<super::user_media_ratings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMediaRatings.def()
    }
}

impl Related<super::user_media_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMediaStates.def()
    }
}

impl Related<super::user_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPreferences.def()
    }
}

impl Related<super::watch_histories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WatchHistories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
