//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_desktops")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "user_desktops_user_id_order_key")]
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(unique_key = "user_desktops_user_id_order_key")]
    pub order: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub wallpaper_mode: Option<String>,
    pub wallpaper_keys: Option<Vec<String>>,
    pub wallpaper_interval: Option<i32>,
    pub wallpaper_dimming: Option<i32>,
    pub wallpaper_blur: Option<i32>,
    pub cell_size: Option<i32>,
    pub grid_width: Option<i32>,
    pub snap_to_grid: Option<bool>,
    pub show_desktop_switcher: Option<bool>,
    pub glass_blur: Option<i32>,
    pub glass_opacity: Option<i32>,
    pub widget_border_radius: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub shortcut_size: Option<String>,
    pub shortcut_label_visible: Option<bool>,
    pub icon_shadow: Option<bool>,
    pub animation_enabled: Option<bool>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::desktop_items::Entity")]
    DesktopItems,
    #[sea_orm(has_many = "super::user_desktop_config::Entity")]
    UserDesktopConfig,
    #[sea_orm(has_many = "super::user_tasks::Entity")]
    UserTasks,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::desktop_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DesktopItems.def()
    }
}

impl Related<super::user_desktop_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserDesktopConfig.def()
    }
}

impl Related<super::user_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserTasks.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
