//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "video", table_name = "user_media_states")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "user_media_states_user_id_book_id_key")]
    pub user_id: Uuid,
    #[sea_orm(unique_key = "user_media_states_user_id_video_item_id_key")]
    pub video_item_id: Option<Uuid>,
    #[sea_orm(unique_key = "user_media_states_user_id_tv_show_id_key")]
    pub tv_show_id: Option<Uuid>,
    #[sea_orm(unique_key = "user_media_states_user_id_episode_id_key")]
    pub episode_id: Option<Uuid>,
    #[sea_orm(unique_key = "user_media_states_user_id_book_id_key")]
    pub book_id: Option<Uuid>,
    pub chapter_id: Option<Uuid>,
    pub resume_position: i32,
    pub play_count: i32,
    pub is_watched: bool,
    pub last_watch_at: Option<DateTimeWithTimeZone>,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    // BookItems relation removed - entity no longer in video app
    #[sea_orm(
        belongs_to = "super::episodes::Entity",
        from = "Column::EpisodeId",
        to = "super::episodes::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Episodes,
    #[sea_orm(
        belongs_to = "super::tv_shows::Entity",
        from = "Column::TvShowId",
        to = "super::tv_shows::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TvShows,
    #[sea_orm(
        belongs_to = "super::video_items::Entity",
        from = "Column::VideoItemId",
        to = "super::video_items::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    VideoItems,
}

// Book items relation removed - entity no longer in video app
/*
impl Related<super::book_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookItems.def()
    }
}
*/

impl Related<super::episodes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Episodes.def()
    }
}

impl Related<super::tv_shows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TvShows.def()
    }
}

impl Related<super::video_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
