//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", unique)]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub password_hash: String,
    pub last_login_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub otp_enabled: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub otp_secret: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ai_agents::Entity")]
    AiAgents,
    #[sea_orm(has_many = "super::ai_conversations::Entity")]
    AiConversations,
    #[sea_orm(has_many = "super::api_keys::Entity")]
    ApiKeys,
    #[sea_orm(has_many = "super::channel_webpush_subscriptions::Entity")]
    ChannelWebpushSubscriptions,
    #[sea_orm(has_many = "super::channels::Entity")]
    Channels,
    #[sea_orm(has_many = "super::desktop_items::Entity")]
    DesktopItems,
    #[sea_orm(has_many = "super::docs_node_comments::Entity")]
    DocsNodeComments,
    #[sea_orm(has_many = "super::docs_node_view_states::Entity")]
    DocsNodeViewStates,
    #[sea_orm(has_one = "super::docs_whiteboard_user_libraries::Entity")]
    DocsWhiteboardUserLibraries,
    #[sea_orm(has_many = "super::download_records::Entity")]
    DownloadRecords,
    #[sea_orm(has_many = "super::file_favorites::Entity")]
    FileFavorites,
    #[sea_orm(has_many = "super::inbox_notifications::Entity")]
    InboxNotifications,
    #[sea_orm(has_many = "super::mail_accounts::Entity")]
    MailAccounts,
    #[sea_orm(has_many = "super::match_histories::Entity")]
    MatchHistories,
    #[sea_orm(has_one = "super::media_playback_states::Entity")]
    MediaPlaybackStates,
    #[sea_orm(has_many = "super::notification_sources::Entity")]
    NotificationSources,
    #[sea_orm(has_many = "super::pass_keys::Entity")]
    PassKeys,
    #[sea_orm(has_many = "super::playback_sessions::Entity")]
    PlaybackSessions,
    #[sea_orm(has_many = "super::scheduled_tasks::Entity")]
    ScheduledTasks,
    #[sea_orm(has_many = "super::search_histories::Entity")]
    SearchHistories,
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
    #[sea_orm(has_many = "super::share_links::Entity")]
    ShareLinks,
    #[sea_orm(has_many = "super::subscription_filters::Entity")]
    SubscriptionFilters,
    #[sea_orm(has_many = "super::subscriptions::Entity")]
    Subscriptions,
    #[sea_orm(has_many = "super::todos::Entity")]
    Todos,
    #[sea_orm(has_one = "super::user_desktop_config::Entity")]
    UserDesktopConfig,
    #[sea_orm(has_many = "super::user_desktops::Entity")]
    UserDesktops,
    #[sea_orm(has_many = "super::user_media_ratings::Entity")]
    UserMediaRatings,
    #[sea_orm(has_many = "super::user_media_states::Entity")]
    UserMediaStates,
    #[sea_orm(has_many = "super::user_memories::Entity")]
    UserMemories,
    #[sea_orm(has_many = "super::user_preferences::Entity")]
    UserPreferences,
    #[sea_orm(has_many = "super::user_tasks::Entity")]
    UserTasks,
    #[sea_orm(has_many = "super::watch_histories::Entity")]
    WatchHistories,
}

impl Related<super::ai_agents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiAgents.def()
    }
}

impl Related<super::ai_conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiConversations.def()
    }
}

impl Related<super::api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeys.def()
    }
}

impl Related<super::channel_webpush_subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelWebpushSubscriptions.def()
    }
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channels.def()
    }
}

impl Related<super::desktop_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DesktopItems.def()
    }
}

impl Related<super::docs_node_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocsNodeComments.def()
    }
}

impl Related<super::docs_node_view_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocsNodeViewStates.def()
    }
}

impl Related<super::docs_whiteboard_user_libraries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocsWhiteboardUserLibraries.def()
    }
}

impl Related<super::download_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DownloadRecords.def()
    }
}

impl Related<super::file_favorites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileFavorites.def()
    }
}

impl Related<super::inbox_notifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InboxNotifications.def()
    }
}

impl Related<super::mail_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MailAccounts.def()
    }
}

impl Related<super::match_histories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MatchHistories.def()
    }
}

impl Related<super::media_playback_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaPlaybackStates.def()
    }
}

impl Related<super::notification_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationSources.def()
    }
}

impl Related<super::pass_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PassKeys.def()
    }
}

impl Related<super::playback_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaybackSessions.def()
    }
}

impl Related<super::scheduled_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScheduledTasks.def()
    }
}

impl Related<super::search_histories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SearchHistories.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::share_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShareLinks.def()
    }
}

impl Related<super::subscription_filters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubscriptionFilters.def()
    }
}

impl Related<super::subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscriptions.def()
    }
}

impl Related<super::todos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Todos.def()
    }
}

impl Related<super::user_desktop_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserDesktopConfig.def()
    }
}

impl Related<super::user_desktops::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserDesktops.def()
    }
}

impl Related<super::user_media_ratings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMediaRatings.def()
    }
}

impl Related<super::user_media_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMediaStates.def()
    }
}

impl Related<super::user_memories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMemories.def()
    }
}

impl Related<super::user_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPreferences.def()
    }
}

impl Related<super::user_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserTasks.def()
    }
}

impl Related<super::watch_histories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WatchHistories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
