//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_desktop_config")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    pub active_desktop_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub wallpaper_mode: String,
    pub wallpaper_keys: Option<Vec<String>>,
    pub wallpaper_interval: i32,
    pub wallpaper_dimming: i32,
    pub wallpaper_blur: i32,
    #[sea_orm(column_type = "Text")]
    pub grid_size: String,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_desktops::Entity",
        from = "Column::ActiveDesktopId",
        to = "super::user_desktops::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    UserDesktops,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::user_desktops::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserDesktops.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
