//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_tasks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub task_type: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_type: Option<String>,
    pub source_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub window_state: String,
    pub window_x: i32,
    pub window_y: i32,
    pub window_width: i32,
    pub window_height: i32,
    pub is_maximized: bool,
    pub z_order: i32,
    #[sea_orm(column_type = "Text")]
    pub route: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    pub sort_order: i32,
    #[sea_orm(column_type = "Text")]
    pub app_name: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub nav_stack: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub pre_max_bounds: Option<Json>,
    #[sea_orm(column_type = "Text")]
    pub render_mode: String,
    pub desktop_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_desktops::Entity",
        from = "Column::DesktopId",
        to = "super::user_desktops::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    UserDesktops,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::user_desktops::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserDesktops.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
