//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_media_ratings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "user_media_ratings_user_id_book_id_key")]
    pub user_id: Uuid,
    #[sea_orm(unique_key = "user_media_ratings_user_id_video_item_id_key")]
    pub video_item_id: Option<Uuid>,
    #[sea_orm(unique_key = "user_media_ratings_user_id_tv_show_id_key")]
    pub tv_show_id: Option<Uuid>,
    #[sea_orm(unique_key = "user_media_ratings_user_id_book_id_key")]
    pub book_id: Option<Uuid>,
    #[sea_orm(column_type = "Double")]
    pub rating: f64,
    #[sea_orm(column_type = "Text", nullable)]
    pub review: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::book_items::Entity",
        from = "Column::BookId",
        to = "super::book_items::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BookItems,
    #[sea_orm(
        belongs_to = "super::tv_shows::Entity",
        from = "Column::TvShowId",
        to = "super::tv_shows::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TvShows,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Users,
    #[sea_orm(
        belongs_to = "super::video_items::Entity",
        from = "Column::VideoItemId",
        to = "super::video_items::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    VideoItems,
}

impl Related<super::book_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookItems.def()
    }
}

impl Related<super::tv_shows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TvShows.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::video_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
