//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "vfs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub config: Option<Json>,
    pub sort_order: i32,
    pub last_scan_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::book_files::Entity")]
    BookFiles,
    #[sea_orm(has_many = "super::docs_spaces::Entity")]
    DocsSpaces,
    #[sea_orm(has_many = "super::file_favorites::Entity")]
    FileFavorites,
    #[sea_orm(has_many = "super::music_files::Entity")]
    MusicFiles,
    #[sea_orm(has_many = "super::photos::Entity")]
    Photos,
    #[sea_orm(has_many = "super::ssh_terminals::Entity")]
    SshTerminals,
    #[sea_orm(has_many = "super::video_files::Entity")]
    VideoFiles,
}

impl Related<super::book_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookFiles.def()
    }
}

impl Related<super::docs_spaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocsSpaces.def()
    }
}

impl Related<super::file_favorites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileFavorites.def()
    }
}

impl Related<super::music_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MusicFiles.def()
    }
}

impl Related<super::photos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Photos.def()
    }
}

impl Related<super::ssh_terminals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SshTerminals.def()
    }
}

impl Related<super::video_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoFiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
