//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "video_cast")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "video_cast_video_item_id_video_person_id_role_key")]
    pub video_item_id: Uuid,
    #[sea_orm(unique_key = "video_cast_video_item_id_video_person_id_role_key")]
    pub video_person_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "video_cast_video_item_id_video_person_id_role_key"
    )]
    pub role: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub character: Option<String>,
    pub sort_order: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::video_items::Entity",
        from = "Column::VideoItemId",
        to = "super::video_items::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    VideoItems,
    #[sea_orm(
        belongs_to = "super::video_persons::Entity",
        from = "Column::VideoPersonId",
        to = "super::video_persons::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    VideoPersons,
}

impl Related<super::video_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoItems.def()
    }
}

impl Related<super::video_persons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoPersons.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
