//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "video", table_name = "video_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "video_items_video_id_imdb_id_key")]
    pub video_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub original_title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sort_title: Option<String>,
    pub year: Option<i32>,
    pub release_date: Option<Date>,
    pub runtime: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub tmdb_rating: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub imdb_rating: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub douban_rating: Option<f64>,
    #[sea_orm(column_type = "Text", nullable, unique_key = "video_items_video_id_tmdb_id_key")]
    pub tmdb_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique_key = "video_items_video_id_imdb_id_key")]
    pub imdb_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub douban_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub jav_number: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub javbus_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub javdb_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub poster_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub backdrop_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub overview: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tagline: Option<String>,
    pub is_adult: bool,
    pub is_favorite: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub original_language: Option<String>,
    pub countries: Option<Vec<String>>,
    pub spoken_languages: Option<Vec<String>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub content_rating: Option<String>,
    pub content_advisories: Option<Vec<String>>,
    pub locked_fields: Option<Vec<String>>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub scraped_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::media_arts::Entity")]
    MediaArts,
    #[sea_orm(has_many = "super::user_media_ratings::Entity")]
    UserMediaRatings,
    #[sea_orm(has_many = "super::user_media_states::Entity")]
    UserMediaStates,
    #[sea_orm(has_many = "super::video_cast::Entity")]
    VideoCast,
    #[sea_orm(has_many = "super::video_collections::Entity")]
    VideoCollections,
    #[sea_orm(has_many = "super::video_files::Entity")]
    VideoFiles,
    #[sea_orm(has_many = "super::video_genres::Entity")]
    VideoGenres,
    #[sea_orm(
        belongs_to = "super::videos::Entity",
        from = "Column::VideoId",
        to = "super::videos::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Videos,
}

impl Related<super::media_arts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaArts.def()
    }
}

impl Related<super::user_media_ratings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMediaRatings.def()
    }
}

impl Related<super::user_media_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMediaStates.def()
    }
}

impl Related<super::video_cast::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoCast.def()
    }
}

impl Related<super::video_collections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoCollections.def()
    }
}

impl Related<super::video_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoFiles.def()
    }
}

impl Related<super::video_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoGenres.def()
    }
}

impl Related<super::videos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Videos.def()
    }
}

impl Related<super::collections::Entity> for Entity {
    fn to() -> RelationDef {
        super::video_collections::Relation::Collections.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::video_collections::Relation::VideoItems.def().rev())
    }
}

impl Related<super::genres::Entity> for Entity {
    fn to() -> RelationDef {
        super::video_genres::Relation::Genres.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::video_genres::Relation::VideoItems.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
