//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "video", table_name = "video_files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "video_files_source_id_path_key")]
    pub source_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", unique_key = "video_files_source_id_path_key")]
    pub path: String,
    #[sea_orm(column_type = "Text")]
    pub filename: String,
    pub size: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mime_type: Option<String>,
    pub duration: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub checksum: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub video_codec: Option<String>,
    pub video_width: Option<i32>,
    pub video_height: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub video_profile: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub hdr_type: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub video_streams: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub audio_streams: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub ffprobe_raw: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub iso_meta: Option<Json>,
    pub is_available: bool,
    pub scanned_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub video_item_id: Option<Uuid>,
    pub episode_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chapters::Entity")]
    Chapters,
    #[sea_orm(
        belongs_to = "super::episodes::Entity",
        from = "Column::EpisodeId",
        to = "super::episodes::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Episodes,
    #[sea_orm(has_many = "super::playback_sessions::Entity")]
    PlaybackSessions,
    #[sea_orm(has_many = "super::subtitles::Entity")]
    Subtitles,
    #[sea_orm(
        belongs_to = "super::vfs::Entity",
        from = "Column::SourceId",
        to = "super::vfs::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Vfs,
    #[sea_orm(
        belongs_to = "super::video_items::Entity",
        from = "Column::VideoItemId",
        to = "super::video_items::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    VideoItems,
    #[sea_orm(has_many = "super::watch_histories::Entity")]
    WatchHistories,
}

impl Related<super::chapters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chapters.def()
    }
}

impl Related<super::episodes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Episodes.def()
    }
}

impl Related<super::playback_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaybackSessions.def()
    }
}

impl Related<super::subtitles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subtitles.def()
    }
}

impl Related<super::vfs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vfs.def()
    }
}

impl Related<super::video_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoItems.def()
    }
}

impl Related<super::watch_histories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WatchHistories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
