//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "video", table_name = "video_persons")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub original_name: Option<String>,
    pub aliases: Option<Vec<String>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub gender: Option<String>,
    pub birthday: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub birthplace: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub profile_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub profile_key: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub biography: Option<String>,
    pub deathday: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub known_for_dept: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub popularity: Option<f64>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub tmdb_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub imdb_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub javbus_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub javdb_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub tpdb_id: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::video_cast::Entity")]
    VideoCast,
}

impl Related<super::video_cast::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoCast.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
